"""
Script to extract and display surface mixing ratios from VULCAN output files.

This script reads the .vul output files (pickled data) generated by the VULCAN simulations,
extracts the surface mixing ratios for specific molecules (N2O, NH3, O3, CH4),
and prints the results in Markdown table format.

It generates two tables:
1. Absolute Surface Abundance (Mixing Ratio).
2. Normalized Abundance relative to the current Earth (Sun A1) baseline.

Usage:
    python extract_surface_values.py
"""

import pickle
import numpy as np
import os
import sys

# =============================================================================
# Configuration
# =============================================================================

# Molecules to analyze
molecules = ['N2O', 'NH3', 'O3', 'CH4']

# Scenarios configuration
scenarios = ['A0', 'A1', 'A2', 'A3']
scenario_names = ['Pre-Agri', 'Present', 'ExoFarm (Mod)', 'ExoFarm (Ext)']

# Stars configuration
stars = [
    {'name': 'Sun (G2V)', 'prefix': 'Earth'},
    {'name': 'TRAPPIST-1e (M8V)', 'prefix': 'Trappist'}
]

# File naming suffix map
suffix_map = {
    'A0': '_A0_PreAgri.vul',
    'A1': '_A1_Current.vul',
    'A2': '_A2_Moderate.vul',
    'A3': '_A3_Extreme.vul'
}

# =============================================================================
# Path Setup
# =============================================================================

# Get absolute paths to key directories to ensure robustness
script_dir = os.path.dirname(os.path.abspath(__file__))
# Project root is 3 levels up from Scripts/Analysis/
project_root = os.path.abspath(os.path.join(script_dir, '../../../'))
output_dir = os.path.join(project_root, 'ExoFarm_Research', 'Results', 'Outputs')

# Verify output directory exists
if not os.path.exists(output_dir):
    print(f"Warning: Output directory not found at {output_dir}")

# =============================================================================
# Helper Functions
# =============================================================================

def get_surface_mixing_ratio_float(filepath, species):
    """
    Extracts the surface mixing ratio of a species from a VULCAN output file.

    Args:
        filepath (str): Path to the .vul pickle file.
        species (str): Name of the chemical species (e.g., 'N2O').

    Returns:
        float or None: The mixing ratio at the surface, or None if not found/error.
    """
    if not os.path.exists(filepath):
        # File might not exist yet if simulation didn't run
        return None

    try:
        with open(filepath, 'rb') as f:
            data = pickle.load(f)
        
        # Check if species exists in the simulation
        if species not in data['variable']['species']:
            return None
            
        sp_idx = data['variable']['species'].index(species)
        
        # Find surface index (assumed to be the index with max pressure)
        # VULCAN usually orders from top to bottom or bottom to top.
        # Max pressure is the surface.
        pco = data['atm']['pco']
        surf_idx = np.argmax(pco)
        
        ymix = data['variable']['ymix'][surf_idx, sp_idx]
        return float(ymix)
        
    except Exception as e:
        # Silently fail for individual files to allow partial reporting
        # print(f"Error reading {filepath}: {e}")
        return None

# =============================================================================
# Main Execution
# =============================================================================

def main():
    # Store values for normalization
    results = {star['name']: {mol: {} for mol in molecules} for star in stars}

    # -------------------------------------------------------------------------
    # 1. Print Absolute Values Tables
    # -------------------------------------------------------------------------
    print("## Tablas de Abundancia Superficial (Mixing Ratio)")
    print("")

    for star in stars:
        print(f"### {star['name']}")
        print("| Molécula | A0 (Pre-Agri) | A1 (Present) | A2 (ExoFarm Mod) | A3 (ExoFarm Ext) |")
        print("| :--- | :---: | :---: | :---: | :---: |")
        
        for mol in molecules:
            row = f"| **{mol}** |"
            for sc, sc_name in zip(scenarios, scenario_names):
                filename = star['prefix'] + suffix_map[sc]
                filepath = os.path.join(output_dir, filename)
                
                val = get_surface_mixing_ratio_float(filepath, mol)
                results[star['name']][mol][sc] = val
                
                if val is not None:
                    display_val = f"{val:.2e}"
                else:
                    display_val = "N/A"
                    
                row += f" {display_val} |"
            print(row)
        print("")

    # -------------------------------------------------------------------------
    # 2. Print Normalized Tables (Relative to Sun A1)
    # -------------------------------------------------------------------------
    print("## Tablas de Abundancia Normalizada (vs. Tierra Actual)")
    print("Valores expresados como múltiplos del nivel actual en la Tierra (Sun A1).")
    print("")

    # Get baseline values (Sun A1)
    baseline = {}
    sun_name = 'Sun (G2V)'
    
    # Ensure we have baselines
    for mol in molecules:
        baseline[mol] = results[sun_name][mol].get('A1')

    for star in stars:
        print(f"### {star['name']} (Normalizado)")
        print("| Molécula | A0 (Pre-Agri) | A1 (Present) | A2 (ExoFarm Mod) | A3 (ExoFarm Ext) |")
        print("| :--- | :---: | :---: | :---: | :---: |")
        
        for mol in molecules:
            row = f"| **{mol}** |"
            base_val = baseline.get(mol)
            
            for sc in scenarios:
                val = results[star['name']][mol].get(sc)
                
                if val is not None and base_val is not None and base_val != 0:
                    ratio = val / base_val
                    
                    # Format based on magnitude
                    if ratio < 0.01:
                        display_val = f"{ratio:.2e}x"
                    elif ratio < 1000:
                        display_val = f"{ratio:.2f}x"
                    else:
                        display_val = f"{ratio:.1e}x"
                else:
                    if val is None:
                        display_val = "N/A"
                    elif base_val is None:
                        display_val = "No Base"
                    else:
                        display_val = "N/A"
                    
                row += f" {display_val} |"
            print(row)
        print("")

if __name__ == "__main__":
    main()
